<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerObd1ltw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerObd1ltw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerObd1ltw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerObd1ltw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerObd1ltw\appProdProjectContainer([
    'container.build_hash' => 'Obd1ltw',
    'container.build_id' => '2044aecc',
    'container.build_time' => 1634907464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerObd1ltw');
