<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPtyagox\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPtyagox/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPtyagox.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPtyagox\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPtyagox\appProdProjectContainer([
    'container.build_hash' => 'Ptyagox',
    'container.build_id' => '9233c69b',
    'container.build_time' => 1635974558,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPtyagox');
