<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEq3ufxk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEq3ufxk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEq3ufxk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEq3ufxk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEq3ufxk\appProdProjectContainer([
    'container.build_hash' => 'Eq3ufxk',
    'container.build_id' => '2db520e4',
    'container.build_time' => 1634907608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEq3ufxk');
