<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCiaixuu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCiaixuu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCiaixuu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCiaixuu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCiaixuu\appProdProjectContainer([
    'container.build_hash' => 'Ciaixuu',
    'container.build_id' => '5f93c6b4',
    'container.build_time' => 1636655178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCiaixuu');
