<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3kk5lfn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3kk5lfn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3kk5lfn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3kk5lfn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3kk5lfn\appProdProjectContainer([
    'container.build_hash' => '3kk5lfn',
    'container.build_id' => 'c8a0dcb7',
    'container.build_time' => 1636663651,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3kk5lfn');
