<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFh5jwch\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFh5jwch/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFh5jwch.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFh5jwch\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFh5jwch\appProdProjectContainer([
    'container.build_hash' => 'Fh5jwch',
    'container.build_id' => 'b40a8fc0',
    'container.build_time' => 1636655107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFh5jwch');
